//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nomina2018.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Nomina2018Entities1 : DbContext
    {
        public Nomina2018Entities1()
            : base("name=Nomina2018Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
    
        public virtual ObjectResult<spListarEmpleadosDet_Result> spListarEmpleadosDet()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spListarEmpleadosDet_Result>("spListarEmpleadosDet");
        }
    }
}
